# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[billing-python.global.parameters]
stack_name = "AWS-Billing"

[billing-python.build.parameters]
cached = true
parallel = true

[billing-python.validate.parameters]
lint = true

[billing-python.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "AWS-Billing-Python"
region = "ap-northeast-1"
disable_rollback = true
image_repositories = []

[billing-python.sync.parameters]
watch = true

[billing-python.local_start_api.parameters]
warm_containers = "EAGER"

[billing-python.local_start_lambda.parameters]
warm_containers = "EAGER"
